[package]
name = "sp1back"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1 = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
rand = "0.8.5"

[lib]
proc-macro = false
test = true
doctest = false 